-- Standalone Key System GUI Script (Roblox Luau)
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local CoreGui = game:GetService("CoreGui")
local Players = game:GetService("Players")
local HttpService = game:GetService("HttpService")

-- Universal Safe GUI Parent Resolver
local function getSafeGuiParent()
    if gethui then
        local success, res = pcall(gethui)
        if success and res then return res end
    end
    local hasCoreGui, core = pcall(function()
        return game:GetService("CoreGui")
    end)
    if hasCoreGui and core then
        local canWrite = pcall(function()
            local f = Instance.new("Folder")
            f.Parent = core
            f:Destroy()
        end)
        if canWrite then return core end
    end
    local lp = Players.LocalPlayer or Players:GetPropertyChangedSignal("LocalPlayer"):Wait() or Players.PlayerAdded:Wait()
    return lp:WaitForChild("PlayerGui", 5) or lp.PlayerGui
end

local parentGui = getSafeGuiParent()

-- Generated by /add: complete home GUI build 2026.08.26.2
-- Clear old copies from every common GUI parent so a legacy supported-games
-- overlay can never remain in front of this new home screen.
local function clearExistingSotariumGui()
    local parentsToCheck = { parentGui }
    pcall(function() table.insert(parentsToCheck, game:GetService("CoreGui")) end)
    pcall(function()
        local player = Players.LocalPlayer
        if player and player:FindFirstChild("PlayerGui") then
            table.insert(parentsToCheck, player.PlayerGui)
        end
    end)
    pcall(function()
        if gethui then table.insert(parentsToCheck, gethui()) end
    end)

    local seen = {}
    for _, guiParent in ipairs(parentsToCheck) do
        if guiParent and not seen[guiParent] then
            seen[guiParent] = true
            for _, child in ipairs(guiParent:GetChildren()) do
                if child:IsA("ScreenGui") and (child.Name == "KeySystemUI" or child.Name == "SotariumKeySystem") then
                    child:Destroy()
                end
            end
        end
    end
end
clearExistingSotariumGui()

-- ScreenGui
local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "KeySystemUI"
ScreenGui.ResetOnSpawn = false
ScreenGui.IgnoreGuiInset = true
ScreenGui.DisplayOrder = 2147483647
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
if syn and syn.protect_gui then
    pcall(syn.protect_gui, ScreenGui)
end
ScreenGui.Parent = parentGui

-- ===========================================
-- Anti-AFK Engine (Boot & Background Protection · by Sotarium)
-- ===========================================
task.spawn(function()
    pcall(function()
        if getgenv().AntiAfkExecuted and game.CoreGui:FindFirstChild("thisoneissocoldww") then
            getgenv().AntiAfkExecuted = false
            getgenv().timerRunning = false
            game.CoreGui.thisoneissocoldww:Destroy()
        end
        getgenv().AntiAfkExecuted = true

        local afkGui = Instance.new("ScreenGui")
        afkGui.Name = "thisoneissocoldww"
        afkGui.ResetOnSpawn = false
        afkGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
        if syn and syn.protect_gui then pcall(syn.protect_gui, afkGui) end
        afkGui.Parent = parentGui

        local afkFrame = Instance.new("Frame")
        afkFrame.Name = "SotariumAntiAfk"
        afkFrame.Parent = afkGui
        afkFrame.BackgroundColor3 = Color3.fromRGB(18, 18, 20)
        afkFrame.BorderSizePixel = 0
        afkFrame.Position = UDim2.new(0.05, 0, 0.1, 0)
        afkFrame.Size = UDim2.new(0, 240, 0, 92)

        local afkCorner = Instance.new("UICorner", afkFrame)
        afkCorner.CornerRadius = UDim.new(0, 8)

        local afkStroke = Instance.new("UIStroke", afkFrame)
        afkStroke.Color = Color3.fromRGB(55, 55, 60)
        afkStroke.Thickness = 1

        local function makeLabel(parent, text, xPos, yPos, xSize, ySize, fontSize, isBold, textColor)
            local lbl = Instance.new("TextLabel", parent)
            lbl.BackgroundTransparency = 1
            lbl.BorderSizePixel = 0
            lbl.Position = UDim2.new(0, xPos, 0, yPos)
            lbl.Size = UDim2.new(0, xSize, 0, ySize)
            lbl.Font = isBold and Enum.Font.GothamBold or Enum.Font.Gotham
            lbl.Text = text
            lbl.TextColor3 = textColor or Color3.fromRGB(255, 255, 255)
            lbl.TextSize = fontSize
            lbl.TextXAlignment = Enum.TextXAlignment.Left
            lbl.TextYAlignment = Enum.TextYAlignment.Center
            return lbl
        end

        local statusDot = Instance.new("Frame", afkFrame)
        statusDot.BackgroundColor3 = Color3.fromRGB(80, 220, 120)
        statusDot.BorderSizePixel = 0
        statusDot.Position = UDim2.new(0, 12, 0, 14)
        statusDot.Size = UDim2.new(0, 6, 0, 6)
        local dotCorner = Instance.new("UICorner", statusDot)
        dotCorner.CornerRadius = UDim.new(1, 0)

        makeLabel(afkFrame, "Anti-AFK · by Sotarium", 24, 8, 180, 18, 11, false, Color3.fromRGB(255, 255, 255))

        local closeBtn = Instance.new("TextButton", afkFrame)
        closeBtn.BackgroundTransparency = 1
        closeBtn.BorderSizePixel = 0
        closeBtn.Position = UDim2.new(1, -28, 0, 8)
        closeBtn.Size = UDim2.new(0, 20, 0, 20)
        closeBtn.Font = Enum.Font.GothamBold
        closeBtn.Text = "x"
        closeBtn.TextColor3 = Color3.fromRGB(150, 150, 160)
        closeBtn.TextSize = 18

        closeBtn.MouseEnter:Connect(function() closeBtn.TextColor3 = Color3.fromRGB(220, 65, 65) end)
        closeBtn.MouseLeave:Connect(function() closeBtn.TextColor3 = Color3.fromRGB(150, 150, 160) end)
        closeBtn.MouseButton1Click:Connect(function()
            getgenv().AntiAfkExecuted = false
            task.wait(0.05)
            afkGui:Destroy()
        end)

        local divider = Instance.new("Frame", afkFrame)
        divider.BackgroundColor3 = Color3.fromRGB(45, 45, 50)
        divider.BorderSizePixel = 0
        divider.Position = UDim2.new(0, 12, 0, 30)
        divider.Size = UDim2.new(1, -24, 0, 1)

        makeLabel(afkFrame, "PING", 12, 38, 72, 14, 9, false, Color3.fromRGB(160, 160, 175))
        makeLabel(afkFrame, "FPS", 92, 38, 72, 14, 9, false, Color3.fromRGB(160, 160, 175))
        makeLabel(afkFrame, "TIME", 162, 38, 72, 14, 9, false, Color3.fromRGB(160, 160, 175))

        local pingLbl = makeLabel(afkFrame, "--", 12, 52, 72, 28, 14, true, Color3.fromRGB(255, 255, 255))
        local fpsLbl = makeLabel(afkFrame, "--", 92, 52, 72, 28, 14, true, Color3.fromRGB(255, 255, 255))
        local timeLbl = makeLabel(afkFrame, "0:00:00", 162, 52, 72, 28, 12, true, Color3.fromRGB(255, 255, 255))

        task.spawn(function()
            while statusDot and statusDot.Parent do
                TweenService:Create(statusDot, TweenInfo.new(0.9, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut), { BackgroundColor3 = Color3.fromRGB(40, 160, 80) }):Play()
                task.wait(0.9)
                TweenService:Create(statusDot, TweenInfo.new(0.9, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut), { BackgroundColor3 = Color3.fromRGB(80, 220, 120) }):Play()
                task.wait(0.9)
            end
        end)

        local draggingAfk = false
        local dragStartPos, frameStartPos
        afkFrame.InputBegan:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
                draggingAfk = true
                dragStartPos = input.Position
                frameStartPos = afkFrame.Position
                input.Changed:Connect(function()
                    if input.UserInputState == Enum.UserInputState.End then draggingAfk = false end
                end)
            end
        end)
        local UserInputService = game:GetService("UserInputService")
        UserInputService.InputChanged:Connect(function(input)
            if draggingAfk and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
                local delta = input.Position - dragStartPos
                TweenService:Create(afkFrame, TweenInfo.new(0.05, Enum.EasingStyle.Sine), {
                    Position = UDim2.new(frameStartPos.X.Scale, frameStartPos.X.Offset + delta.X, frameStartPos.Y.Scale, frameStartPos.Y.Offset + delta.Y)
                }):Play()
            end
        end)

        local lp = Players.LocalPlayer or Players.PlayerAdded:Wait()
        local VirtualUser = game:GetService("VirtualUser")
        lp.Idled:Connect(function()
            VirtualUser:CaptureController()
            VirtualUser:ClickButton2(Vector2.new())
        end)

        local lastTick = tick()
        local frameTimes = {}
        RunService.RenderStepped:Connect(function()
            local now = tick()
            for i = #frameTimes, 1, -1 do
                frameTimes[i + 1] = frameTimes[i] >= now - 1 and frameTimes[i] or nil
            end
            frameTimes[1] = now
            if fpsLbl and fpsLbl.Parent then
                fpsLbl.Text = tostring(math.floor(tick() - lastTick >= 1 and #frameTimes or #frameTimes / (tick() - lastTick)))
            end
        end)

        task.spawn(function()
            while pingLbl and pingLbl.Parent do
                local ok, result = pcall(function()
                    return game:GetService("Stats"):FindFirstChild("PerformanceStats").Ping:GetValue()
                end)
                if ok and result then
                    pingLbl.Text = tostring(math.floor(result)) .. "ms"
                end
                task.wait(1)
            end
        end)

        local secs, mins, hrs = 0, 0, 0
        getgenv().timerRunning = true
        task.spawn(function()
            while getgenv().timerRunning and timeLbl and timeLbl.Parent do
                task.wait(1)
                secs = secs + 1
                if secs >= 60 then secs = 0; mins = mins + 1 end
                if mins >= 60 then mins = 0; hrs = hrs + 1 end
                timeLbl.Text = string.format("%d:%02d:%02d", hrs, mins, secs)
            end
        end)
    end)
end)

-- Main Container Window
local MainFrame = Instance.new("Frame")
MainFrame.Name = "MainFrame"
MainFrame.Size = UDim2.new(0, 720, 0, 440)
MainFrame.Position = UDim2.new(0.5, -360, 0.5, -220)
MainFrame.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
MainFrame.BorderSizePixel = 0
MainFrame.ClipsDescendants = true
MainFrame.Parent = ScreenGui

local MainCorner = Instance.new("UICorner")
MainCorner.CornerRadius = UDim.new(0, 14)
MainCorner.Parent = MainFrame

local MainStroke = Instance.new("UIStroke")
MainStroke.Color = Color3.fromRGB(30, 30, 30)
MainStroke.Thickness = 1
MainStroke.Parent = MainFrame

-- __SOTARIUM_GENERATED_GAME_CONFIG__

-- ===========================================
-- GitHub & Online Custom Asset Loader with Failovers
-- ===========================================
local function toRawGithubUrl(url)
    if url:find("github.com") and url:find("/blob/") then
        return url:gsub("github.com", "raw.githubusercontent.com"):gsub("/blob/", "/")
    end
    return url
end

local function httpGetSafe(url)
    local rawUrl = toRawGithubUrl(url)
    local res = nil
    pcall(function()
        if syn and syn.request then
            local r = syn.request({Url = rawUrl, Method = "GET"})
            if r and r.StatusCode == 200 and r.Body and #r.Body > 0 then res = r.Body end
        elseif http and http.request then
            local r = http.request({Url = rawUrl, Method = "GET"})
            if r and r.StatusCode == 200 and r.Body and #r.Body > 0 then res = r.Body end
        elseif http_request then
            local r = http_request({Url = rawUrl, Method = "GET"})
            if r and r.StatusCode == 200 and r.Body and #r.Body > 0 then res = r.Body end
        elseif request then
            local r = request({Url = rawUrl, Method = "GET"})
            if r and r.StatusCode == 200 and r.Body and #r.Body > 0 then res = r.Body end
        else
            res = game:HttpGet(rawUrl)
        end
    end)
    return res
end

local function loadRemoteAsset(fileName, primaryUrl, fallbackUrl)
    if getcustomasset and writefile then
        local success, assetId = pcall(function()
            local localPath = "sotarium_" .. fileName
            if not isfile or not isfile(localPath) then
                local body = httpGetSafe(primaryUrl)
                if (not body or #body < 100) and fallbackUrl then
                    body = httpGetSafe(fallbackUrl)
                end
                if body and #body > 100 then
                    writefile(localPath, body)
                end
            end
            return getcustomasset(localPath)
        end)
        if success and assetId then
            return assetId
        end
    end
    return "rbxassetid://13543208759"
end

-- Download exact assets
local GamesAssetId = loadRemoteAsset("games.png", "https://raw.githubusercontent.com/Yousoterium/Sotarium/main/images/games.png")
local SanDiegoAssetId = loadRemoteAsset("sandiego_v2.png", "https://raw.githubusercontent.com/Yousoterium/Sotarium/main/images/game1.png", "https://tr.rbxcdn.com/180DAY-a8e7148123010ced8bdce8c0542cc662/768/432/Image/Webp/noFilter")
local LucideLoaderAssetId = loadRemoteAsset("loader_256.png", "https://raw.githubusercontent.com/latte-soft/lucide-roblox/master/icons/compiled/256px/loader.png")
local LucideArrowLeftAssetId = loadRemoteAsset("arrow_left_256.png", "https://raw.githubusercontent.com/latte-soft/lucide-roblox/master/icons/compiled/256px/arrow-left.png")

-- ===========================================
-- Lucide Verified Icons
-- ===========================================
local LucideIcons = {
    ["rocket"]        = "rbxassetid://10734934585",
    ["key"]           = "rbxassetid://10723416652",
    ["x-circle"]      = "rbxassetid://10747384552",
    ["check"]         = "rbxassetid://10709790644",
    ["alert-circle"]  = "rbxassetid://10709752035",
    ["gamepad"]       = "rbxassetid://10734940040",
    ["arrow-left"]    = "rbxassetid://10709789907",
    ["x"]             = "rbxassetid://10747384394",
    ["minus"]         = "rbxassetid://10734896206",
    ["maximize"]      = "rbxassetid://10734942183"
}

-- ===========================================
-- Contextual Notification System
-- ===========================================
local NotifContainer = Instance.new("Frame")
NotifContainer.Name = "NotifContainer"
NotifContainer.Size = UDim2.new(0, 310, 1, -20)
NotifContainer.Position = UDim2.new(1, -325, 0, 10)
NotifContainer.BackgroundTransparency = 1
NotifContainer.ZIndex = 60
NotifContainer.Parent = MainFrame

local NotifLayout = Instance.new("UIListLayout")
NotifLayout.FillDirection = Enum.FillDirection.Vertical
NotifLayout.VerticalAlignment = Enum.VerticalAlignment.Bottom
NotifLayout.HorizontalAlignment = Enum.HorizontalAlignment.Right
NotifLayout.SortOrder = Enum.SortOrder.LayoutOrder
NotifLayout.Padding = UDim.new(0, 10)
NotifLayout.Parent = NotifContainer

local function showNotification(text, notifType, duration)
    notifType = notifType or "info"
    duration = duration or 2.8

    local iconId = LucideIcons["alert-circle"]
    local iconColor = Color3.fromRGB(220, 220, 220)

    if notifType == "warning" or notifType == "error" then
        iconId = LucideIcons["x-circle"]
        iconColor = Color3.fromRGB(245, 75, 75)
    elseif notifType == "launch" or notifType == "rocket" then
        iconId = LucideIcons["rocket"]
        iconColor = Color3.fromRGB(255, 255, 255)
    elseif notifType == "key" or notifType == "copy" then
        iconId = LucideIcons["key"]
        iconColor = Color3.fromRGB(220, 220, 220)
    elseif notifType == "gamepad" or notifType == "game" then
        iconId = LucideIcons["gamepad"]
        iconColor = Color3.fromRGB(255, 255, 255)
    elseif notifType == "success" or notifType == "games_loaded" then
        iconId = LucideIcons["check"]
        iconColor = Color3.fromRGB(34, 215, 64)
    end

    local toast = Instance.new("Frame")
    toast.Name = "Toast"
    toast.Size = UDim2.new(1, 0, 0, 42)
    toast.BackgroundColor3 = Color3.fromRGB(18, 18, 18)
    toast.BorderSizePixel = 0
    toast.ClipsDescendants = true
    toast.BackgroundTransparency = 1
    toast.ZIndex = 61
    toast.Parent = NotifContainer

    local toastCorner = Instance.new("UICorner")
    toastCorner.CornerRadius = UDim.new(0, 8)
    toastCorner.Parent = toast

    local toastStroke = Instance.new("UIStroke")
    toastStroke.Color = Color3.fromRGB(36, 36, 36)
    toastStroke.Thickness = 1
    toastStroke.Transparency = 1
    toastStroke.Parent = toast

    -- Context Icon
    local iconImage = Instance.new("ImageLabel")
    iconImage.Size = UDim2.new(0, 18, 0, 18)
    iconImage.Position = UDim2.new(0, 12, 0.5, -9)
    iconImage.BackgroundTransparency = 1
    iconImage.Image = iconId
    iconImage.ImageColor3 = iconColor
    iconImage.ImageTransparency = 1
    iconImage.ZIndex = 62
    iconImage.Parent = toast

    -- Message Text
    local msgLabel = Instance.new("TextLabel")
    msgLabel.Size = UDim2.new(1, -66, 1, -4)
    msgLabel.Position = UDim2.new(0, 38, 0, 0)
    msgLabel.BackgroundTransparency = 1
    msgLabel.Font = Enum.Font.GothamMedium
    msgLabel.Text = text
    msgLabel.TextColor3 = Color3.fromRGB(240, 240, 240)
    msgLabel.TextSize = 13
    msgLabel.TextXAlignment = Enum.TextXAlignment.Left
    msgLabel.TextTransparency = 1
    msgLabel.ZIndex = 62
    msgLabel.Parent = toast

    -- Close (X) Button
    local closeBtn = Instance.new("ImageButton")
    closeBtn.Name = "CloseBtn"
    closeBtn.Size = UDim2.new(0, 14, 0, 14)
    closeBtn.Position = UDim2.new(1, -24, 0.5, -7)
    closeBtn.BackgroundTransparency = 1
    closeBtn.Image = LucideIcons["x"]
    closeBtn.ImageColor3 = Color3.fromRGB(150, 150, 150)
    closeBtn.ImageTransparency = 1
    closeBtn.ZIndex = 63
    closeBtn.Parent = toast

    closeBtn.MouseEnter:Connect(function()
        TweenService:Create(closeBtn, TweenInfo.new(0.15), {ImageColor3 = Color3.fromRGB(255, 255, 255)}):Play()
    end)
    closeBtn.MouseLeave:Connect(function()
        TweenService:Create(closeBtn, TweenInfo.new(0.15), {ImageColor3 = Color3.fromRGB(150, 150, 150)}):Play()
    end)

    -- Bottom Countdown Line
    local progressBar = Instance.new("Frame")
    progressBar.Name = "ProgressBar"
    progressBar.Size = UDim2.new(1, 0, 0, 2)
    progressBar.Position = UDim2.new(0, 0, 1, -2)
    progressBar.BackgroundColor3 = ((notifType == "success" or notifType == "games_loaded") and Color3.fromRGB(34, 215, 64)) or Color3.fromRGB(255, 255, 255)
    progressBar.BorderSizePixel = 0
    progressBar.BackgroundTransparency = 1
    progressBar.ZIndex = 64
    progressBar.Parent = toast

    -- Smooth Fade In
    TweenService:Create(toast, TweenInfo.new(0.2), {BackgroundTransparency = 0}):Play()
    TweenService:Create(toastStroke, TweenInfo.new(0.2), {Transparency = 0}):Play()
    TweenService:Create(iconImage, TweenInfo.new(0.2), {ImageTransparency = 0}):Play()
    TweenService:Create(msgLabel, TweenInfo.new(0.2), {TextTransparency = 0}):Play()
    TweenService:Create(closeBtn, TweenInfo.new(0.2), {ImageTransparency = 0}):Play()
    TweenService:Create(progressBar, TweenInfo.new(0.2), {BackgroundTransparency = 0}):Play()

    -- Countdown Animation
    local barTween = TweenService:Create(progressBar, TweenInfo.new(duration, Enum.EasingStyle.Linear), {
        Size = UDim2.new(0, 0, 0, 2)
    })
    barTween:Play()

    local isDismissed = false
    local function dismiss()
        if isDismissed then return end
        isDismissed = true
        local fadeOut = TweenService:Create(toast, TweenInfo.new(0.2), {BackgroundTransparency = 1})
        TweenService:Create(toastStroke, TweenInfo.new(0.2), {Transparency = 1}):Play()
        TweenService:Create(iconImage, TweenInfo.new(0.2), {ImageTransparency = 1}):Play()
        TweenService:Create(msgLabel, TweenInfo.new(0.2), {TextTransparency = 1}):Play()
        TweenService:Create(closeBtn, TweenInfo.new(0.2), {ImageTransparency = 1}):Play()
        TweenService:Create(progressBar, TweenInfo.new(0.2), {BackgroundTransparency = 1}):Play()
        fadeOut:Play()
        fadeOut.Completed:Connect(function()
            toast:Destroy()
        end)
    end

    closeBtn.MouseButton1Click:Connect(dismiss)
    barTween.Completed:Connect(dismiss)
end

-- ===========================================
-- Top Bar (Dragging & Window Controls - Visible on Every Page)
-- ===========================================
local TopBar = Instance.new("Frame")
TopBar.Name = "TopBar"
TopBar.Size = UDim2.new(1, 0, 0, 42)
TopBar.BackgroundTransparency = 1
TopBar.ZIndex = 60
TopBar.Parent = MainFrame

local Controls = Instance.new("Frame")
Controls.Name = "Controls"
Controls.Size = UDim2.new(0, 105, 1, 0)
Controls.Position = UDim2.new(1, -115, 0, 0)
Controls.BackgroundTransparency = 1
Controls.ZIndex = 61
Controls.Parent = TopBar

local ControlsLayout = Instance.new("UIListLayout")
ControlsLayout.FillDirection = Enum.FillDirection.Horizontal
ControlsLayout.HorizontalAlignment = Enum.HorizontalAlignment.Right
ControlsLayout.VerticalAlignment = Enum.VerticalAlignment.Center
ControlsLayout.SortOrder = Enum.SortOrder.LayoutOrder
ControlsLayout.Padding = UDim.new(0, 16)
ControlsLayout.Parent = Controls

local function createButtonContainer(name, layoutOrder)
    local btn = Instance.new("TextButton")
    btn.Name = name
    btn.Size = UDim2.new(0, 16, 0, 16)
    btn.BackgroundTransparency = 1
    btn.Text = ""
    btn.LayoutOrder = layoutOrder
    btn.ZIndex = 62
    btn.Parent = Controls
    return btn
end

-- Minimize (-)
local MinBtn = createButtonContainer("MinimizeBtn", 1)
local MinBar = Instance.new("Frame")
MinBar.Size = UDim2.new(0, 12, 0, 2)
MinBar.Position = UDim2.new(0.5, -6, 0.5, 0)
MinBar.BackgroundColor3 = Color3.fromRGB(150, 150, 150)
MinBar.BorderSizePixel = 0
MinBar.Parent = MinBtn

local isMinimized = false
local defaultSize = MainFrame.Size
MinBtn.MouseButton1Click:Connect(function()
    isMinimized = not isMinimized
    local targetSize = isMinimized and UDim2.new(0, 720, 0, 42) or defaultSize
    TweenService:Create(MainFrame, TweenInfo.new(0.3, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {Size = targetSize}):Play()
end)

MinBtn.MouseEnter:Connect(function() TweenService:Create(MinBar, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(255, 255, 255)}):Play() end)
MinBtn.MouseLeave:Connect(function() TweenService:Create(MinBar, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(150, 150, 150)}):Play() end)

-- Fullscreen (4 corner brackets)
local FullscreenBtn = createButtonContainer("FullscreenBtn", 2)
local cornerLines = {}

local function createCornerBracket(hSize, vSize, hPos, vPos)
    local hLine = Instance.new("Frame")
    hLine.Size = hSize; hLine.Position = hPos; hLine.BackgroundColor3 = Color3.fromRGB(150, 150, 150); hLine.BorderSizePixel = 0; hLine.Parent = FullscreenBtn
    table.insert(cornerLines, hLine)
    local vLine = Instance.new("Frame")
    vLine.Size = vSize; vLine.Position = vPos; vLine.BackgroundColor3 = Color3.fromRGB(150, 150, 150); vLine.BorderSizePixel = 0; vLine.Parent = FullscreenBtn
    table.insert(cornerLines, vLine)
end

createCornerBracket(UDim2.new(0, 4, 0, 1.5), UDim2.new(0, 1.5, 0, 4), UDim2.new(0, 2, 0, 2), UDim2.new(0, 2, 0, 2))
createCornerBracket(UDim2.new(0, 4, 0, 1.5), UDim2.new(0, 1.5, 0, 4), UDim2.new(1, -6, 0, 2), UDim2.new(1, -3.5, 0, 2))
createCornerBracket(UDim2.new(0, 4, 0, 1.5), UDim2.new(0, 1.5, 0, 4), UDim2.new(0, 2, 1, -3.5), UDim2.new(0, 2, 1, -6))
createCornerBracket(UDim2.new(0, 4, 0, 1.5), UDim2.new(0, 1.5, 0, 4), UDim2.new(1, -6, 1, -3.5), UDim2.new(1, -3.5, 1, -6))

FullscreenBtn.MouseEnter:Connect(function()
    for _, l in ipairs(cornerLines) do TweenService:Create(l, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(255, 255, 255)}):Play() end
end)
FullscreenBtn.MouseLeave:Connect(function()
    for _, l in ipairs(cornerLines) do TweenService:Create(l, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(150, 150, 150)}):Play() end
end)

local isMaximized = false
local preMaxPos, preMaxSize
FullscreenBtn.MouseButton1Click:Connect(function()
    isMaximized = not isMaximized
    if isMaximized then
        preMaxPos = MainFrame.Position
        preMaxSize = MainFrame.Size
        TweenService:Create(MainFrame, TweenInfo.new(0.3, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
            Size = UDim2.new(0.94, 0, 0.9, 0),
            Position = UDim2.new(0.03, 0, 0.05, 0)
        }):Play()
    else
        TweenService:Create(MainFrame, TweenInfo.new(0.3, Enum.EasingStyle.Quart, Enum.EasingDirection.Out), {
            Size = preMaxSize or defaultSize,
            Position = preMaxPos or UDim2.new(0.5, -360, 0.5, -220)
        }):Play()
    end
end)

-- Close (X)
local CloseBtn = createButtonContainer("CloseBtn", 3)
local closeLines = {}

local function createXLine(rotation)
    local line = Instance.new("Frame")
    line.Size = UDim2.new(0, 14, 0, 1.5)
    line.Position = UDim2.new(0.5, -7, 0.5, -0.75)
    line.BackgroundColor3 = Color3.fromRGB(150, 150, 150)
    line.BorderSizePixel = 0
    line.Rotation = rotation
    line.Parent = CloseBtn
    table.insert(closeLines, line)
end
createXLine(45); createXLine(-45)

CloseBtn.MouseEnter:Connect(function()
    for _, l in ipairs(closeLines) do TweenService:Create(l, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(255, 255, 255)}):Play() end
end)
CloseBtn.MouseLeave:Connect(function()
    for _, l in ipairs(closeLines) do TweenService:Create(l, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(150, 150, 150)}):Play() end
end)
CloseBtn.MouseButton1Click:Connect(function()
    local t = TweenService:Create(MainFrame, TweenInfo.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.In), {
        Size = UDim2.new(0, 0, 0, 0),
        Position = UDim2.new(MainFrame.Position.X.Scale, MainFrame.Position.X.Offset + (MainFrame.AbsoluteSize.X/2), MainFrame.Position.Y.Scale, MainFrame.Position.Y.Offset + (MainFrame.AbsoluteSize.Y/2))
    })
    t:Play()
    t.Completed:Connect(function() ScreenGui:Destroy() end)
end)

-- ===========================================
-- Center Main Content
-- ===========================================
local ContentFrame = Instance.new("Frame")
ContentFrame.Name = "Content"
ContentFrame.Size = UDim2.new(0, 320, 0, 230)
ContentFrame.Position = UDim2.new(0.5, -160, 0.5, -100)
ContentFrame.BackgroundTransparency = 1
ContentFrame.Parent = MainFrame

local ContentLayout = Instance.new("UIListLayout")
ContentLayout.FillDirection = Enum.FillDirection.Vertical
ContentLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
ContentLayout.VerticalAlignment = Enum.VerticalAlignment.Center
ContentLayout.SortOrder = Enum.SortOrder.LayoutOrder
ContentLayout.Padding = UDim.new(0, 12)
ContentLayout.Parent = ContentFrame

-- Title
local TitleLabel = Instance.new("TextLabel")
TitleLabel.Name = "Title"
TitleLabel.Size = UDim2.new(1, 0, 0, 30)
TitleLabel.BackgroundTransparency = 1
TitleLabel.Font = Enum.Font.GothamBold
TitleLabel.Text = "Get your access key"
TitleLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
TitleLabel.TextSize = 22
TitleLabel.LayoutOrder = 1
TitleLabel.Parent = ContentFrame

-- Key Input Container
local KeyInputFrame = Instance.new("Frame")
KeyInputFrame.Name = "KeyInputFrame"
KeyInputFrame.Size = UDim2.new(1, 0, 0, 44)
KeyInputFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
KeyInputFrame.BorderSizePixel = 0
KeyInputFrame.LayoutOrder = 2
KeyInputFrame.Parent = ContentFrame

local KeyInputCorner = Instance.new("UICorner")
KeyInputCorner.CornerRadius = UDim.new(0, 10)
KeyInputCorner.Parent = KeyInputFrame

local KeyInputStroke = Instance.new("UIStroke")
KeyInputStroke.Color = Color3.fromRGB(34, 34, 34)
KeyInputStroke.Thickness = 1
KeyInputStroke.Parent = KeyInputFrame

local KeyTextBox = Instance.new("TextBox")
KeyTextBox.Name = "KeyTextBox"
KeyTextBox.Size = UDim2.new(1, -24, 1, 0)
KeyTextBox.Position = UDim2.new(0, 12, 0, 0)
KeyTextBox.BackgroundTransparency = 1
KeyTextBox.Font = Enum.Font.GothamMedium
KeyTextBox.PlaceholderText = "Key"
KeyTextBox.PlaceholderColor3 = Color3.fromRGB(115, 115, 115)
KeyTextBox.Text = ""
KeyTextBox.TextColor3 = Color3.fromRGB(240, 240, 240)
KeyTextBox.TextSize = 14
KeyTextBox.ClearTextOnFocus = false
KeyTextBox.Parent = KeyInputFrame

-- Side-by-Side Buttons Row (Submit + Get Key)
local ButtonsRow = Instance.new("Frame")
ButtonsRow.Name = "ButtonsRow"
ButtonsRow.Size = UDim2.new(1, 0, 0, 44)
ButtonsRow.BackgroundTransparency = 1
ButtonsRow.LayoutOrder = 3
ButtonsRow.Parent = ContentFrame

local ButtonsRowLayout = Instance.new("UIListLayout")
ButtonsRowLayout.FillDirection = Enum.FillDirection.Horizontal
ButtonsRowLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
ButtonsRowLayout.VerticalAlignment = Enum.VerticalAlignment.Center
ButtonsRowLayout.SortOrder = Enum.SortOrder.LayoutOrder
ButtonsRowLayout.Padding = UDim.new(0, 10)
ButtonsRowLayout.Parent = ButtonsRow

-- 1. Submit / Redeem Button (Left)
local SubmitButton = Instance.new("TextButton")
SubmitButton.Name = "SubmitButton"
SubmitButton.Size = UDim2.new(0.5, -5, 1, 0)
SubmitButton.BackgroundColor3 = Color3.fromRGB(120, 120, 120)
SubmitButton.BorderSizePixel = 0
SubmitButton.Font = Enum.Font.GothamBold
SubmitButton.Text = "Submit"
SubmitButton.TextColor3 = Color3.fromRGB(18, 18, 18)
SubmitButton.TextSize = 14
SubmitButton.AutoButtonColor = false
SubmitButton.LayoutOrder = 1
SubmitButton.Parent = ButtonsRow

local SubmitCorner = Instance.new("UICorner")
SubmitCorner.CornerRadius = UDim.new(0, 10)
SubmitCorner.Parent = SubmitButton

-- 2. Get Key Button (Right)
local GetKeyButton = Instance.new("TextButton")
GetKeyButton.Name = "GetKeyButton"
GetKeyButton.Size = UDim2.new(0.5, -5, 1, 0)
GetKeyButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
GetKeyButton.BorderSizePixel = 0
GetKeyButton.Font = Enum.Font.GothamBold
GetKeyButton.Text = "Get Key"
GetKeyButton.TextColor3 = Color3.fromRGB(240, 240, 240)
GetKeyButton.TextSize = 14
GetKeyButton.AutoButtonColor = false
GetKeyButton.LayoutOrder = 2
GetKeyButton.Parent = ButtonsRow

local GetKeyCorner = Instance.new("UICorner")
GetKeyCorner.CornerRadius = UDim.new(0, 10)
GetKeyCorner.Parent = GetKeyButton

local GetKeyStroke = Instance.new("UIStroke")
GetKeyStroke.Color = Color3.fromRGB(34, 34, 34)
GetKeyStroke.Thickness = 1
GetKeyStroke.Parent = GetKeyButton

GetKeyButton.MouseEnter:Connect(function() TweenService:Create(GetKeyButton, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(26, 26, 26)}):Play() end)
GetKeyButton.MouseLeave:Connect(function() TweenService:Create(GetKeyButton, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(20, 20, 20)}):Play() end)

-- 3. Supported Games Button (Full Width Underneath)
local SupportedGamesButton = Instance.new("TextButton")
SupportedGamesButton.Name = "SupportedGamesButton"
SupportedGamesButton.Size = UDim2.new(1, 0, 0, 44)
SupportedGamesButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
SupportedGamesButton.BorderSizePixel = 0
SupportedGamesButton.Font = Enum.Font.GothamBold
SupportedGamesButton.Text = "Supported Games"
SupportedGamesButton.TextColor3 = Color3.fromRGB(220, 220, 220)
SupportedGamesButton.TextSize = 14
SupportedGamesButton.AutoButtonColor = false
SupportedGamesButton.LayoutOrder = 4
SupportedGamesButton.Parent = ContentFrame

local GamesCorner = Instance.new("UICorner")
GamesCorner.CornerRadius = UDim.new(0, 10)
GamesCorner.Parent = SupportedGamesButton

local GamesStroke = Instance.new("UIStroke")
GamesStroke.Color = Color3.fromRGB(34, 34, 34)
GamesStroke.Thickness = 1
GamesStroke.Parent = SupportedGamesButton

SupportedGamesButton.MouseEnter:Connect(function()
    TweenService:Create(SupportedGamesButton, TweenInfo.new(0.15), {
        BackgroundColor3 = Color3.fromRGB(26, 26, 26),
        TextColor3 = Color3.fromRGB(255, 255, 255)
    }):Play()
end)
SupportedGamesButton.MouseLeave:Connect(function()
    TweenService:Create(SupportedGamesButton, TweenInfo.new(0.15), {
        BackgroundColor3 = Color3.fromRGB(20, 20, 20),
        TextColor3 = Color3.fromRGB(220, 220, 220)
    }):Play()
end)

-- 4. Discord Button (Full-width pill, copy-only action)
local JoinDiscordButton = Instance.new("TextButton")
JoinDiscordButton.Name = "JoinDiscordButton"
JoinDiscordButton.Size = UDim2.new(1, 0, 0, 42)
JoinDiscordButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
JoinDiscordButton.BorderSizePixel = 0
JoinDiscordButton.Font = Enum.Font.GothamBold
JoinDiscordButton.Text = "Join Discord"
JoinDiscordButton.TextColor3 = Color3.fromRGB(220, 220, 220)
JoinDiscordButton.TextSize = 14
JoinDiscordButton.AutoButtonColor = false
JoinDiscordButton.LayoutOrder = 5
JoinDiscordButton.Parent = ContentFrame

local DiscordCorner = Instance.new("UICorner")
DiscordCorner.CornerRadius = UDim.new(1, 0)
DiscordCorner.Parent = JoinDiscordButton

local DiscordStroke = Instance.new("UIStroke")
DiscordStroke.Color = Color3.fromRGB(34, 34, 34)
DiscordStroke.Thickness = 1
DiscordStroke.Parent = JoinDiscordButton

JoinDiscordButton.MouseEnter:Connect(function()
    TweenService:Create(JoinDiscordButton, TweenInfo.new(0.15), {
        BackgroundColor3 = Color3.fromRGB(26, 26, 26),
        TextColor3 = Color3.fromRGB(255, 255, 255)
    }):Play()
end)

JoinDiscordButton.MouseLeave:Connect(function()
    TweenService:Create(JoinDiscordButton, TweenInfo.new(0.15), {
        BackgroundColor3 = Color3.fromRGB(20, 20, 20),
        TextColor3 = Color3.fromRGB(220, 220, 220)
    }):Play()
end)

JoinDiscordButton.MouseButton1Click:Connect(function()
    if setclipboard then
        pcall(setclipboard, "https://discord.gg/3aghbJBybQ")
    end
    showNotification("Link for Discord copied!", "key", 2.5)
end)

-- Key input watcher: White when text entered, black text
KeyTextBox:GetPropertyChangedSignal("Text"):Connect(function()
    local text = KeyTextBox.Text:gsub("%s+", "")
    if #text > 0 then
        TweenService:Create(SubmitButton, TweenInfo.new(0.2), {
            BackgroundColor3 = Color3.fromRGB(255, 255, 255),
            TextColor3 = Color3.fromRGB(0, 0, 0)
        }):Play()
    else
        TweenService:Create(SubmitButton, TweenInfo.new(0.2), {
            BackgroundColor3 = Color3.fromRGB(120, 120, 120),
            TextColor3 = Color3.fromRGB(18, 18, 18)
        }):Play()
    end
end)

-- Function to Enable/Disable Menu Controls
local function setMenuControlsEnabled(enabled)
    SubmitButton.Active = enabled
    GetKeyButton.Active = enabled
    SupportedGamesButton.Active = enabled
    JoinDiscordButton.Active = enabled
    KeyTextBox.TextEditable = enabled
    KeyTextBox.Active = enabled
end

-- ===========================================
-- Supported Games Panel (opens only on demand)
-- ===========================================
local SupportedGamesPanel = Instance.new("Frame")
SupportedGamesPanel.Name = "SupportedGamesPanel"
SupportedGamesPanel.Size = UDim2.new(1, 0, 1, 0)
SupportedGamesPanel.Position = UDim2.new(0, 0, 0, 0)
SupportedGamesPanel.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
SupportedGamesPanel.BorderSizePixel = 0
SupportedGamesPanel.ClipsDescendants = true
SupportedGamesPanel.Visible = false
SupportedGamesPanel.ZIndex = 40
SupportedGamesPanel.Parent = MainFrame

local SupportedPanelCorner = Instance.new("UICorner")
SupportedPanelCorner.CornerRadius = UDim.new(0, 14)
SupportedPanelCorner.Parent = SupportedGamesPanel

local SupportedPanelHeader = Instance.new("Frame")
SupportedPanelHeader.Name = "SupportedPanelHeader"
SupportedPanelHeader.Size = UDim2.new(1, 0, 0, 46)
SupportedPanelHeader.BackgroundColor3 = Color3.fromRGB(18, 18, 18)
SupportedPanelHeader.BorderSizePixel = 0
SupportedPanelHeader.ZIndex = 41
SupportedPanelHeader.Parent = SupportedGamesPanel

local SupportedHeaderDivider = Instance.new("Frame")
SupportedHeaderDivider.Size = UDim2.new(1, 0, 0, 1)
SupportedHeaderDivider.Position = UDim2.new(0, 0, 1, -1)
SupportedHeaderDivider.BackgroundColor3 = Color3.fromRGB(36, 36, 36)
SupportedHeaderDivider.BorderSizePixel = 0
SupportedHeaderDivider.ZIndex = 42
SupportedHeaderDivider.Parent = SupportedPanelHeader

local SupportedPanelTitle = Instance.new("TextLabel")
SupportedPanelTitle.Size = UDim2.new(1, -160, 1, 0)
SupportedPanelTitle.Position = UDim2.new(0, 84, 0, 0)
SupportedPanelTitle.BackgroundTransparency = 1
SupportedPanelTitle.Font = Enum.Font.GothamBold
SupportedPanelTitle.Text = "Supported Games"
SupportedPanelTitle.TextColor3 = Color3.fromRGB(255, 255, 255)
SupportedPanelTitle.TextSize = 15
SupportedPanelTitle.TextXAlignment = Enum.TextXAlignment.Left
SupportedPanelTitle.ZIndex = 42
SupportedPanelTitle.Parent = SupportedPanelHeader

local SupportedBackButton = Instance.new("TextButton")
SupportedBackButton.Name = "SupportedBackButton"
SupportedBackButton.Size = UDim2.new(0, 66, 0, 28)
SupportedBackButton.Position = UDim2.new(0, 12, 0.5, -14)
SupportedBackButton.BackgroundColor3 = Color3.fromRGB(28, 28, 28)
SupportedBackButton.BorderSizePixel = 0
SupportedBackButton.Font = Enum.Font.GothamBold
SupportedBackButton.Text = "Back"
SupportedBackButton.TextColor3 = Color3.fromRGB(230, 230, 230)
SupportedBackButton.TextSize = 12
SupportedBackButton.AutoButtonColor = false
SupportedBackButton.ZIndex = 43
SupportedBackButton.Parent = SupportedPanelHeader

local SupportedBackCorner = Instance.new("UICorner")
SupportedBackCorner.CornerRadius = UDim.new(0, 7)
SupportedBackCorner.Parent = SupportedBackButton

local SupportedGrid = Instance.new("ScrollingFrame")
SupportedGrid.Name = "SupportedGrid"
SupportedGrid.Size = UDim2.new(1, -32, 1, -68)
SupportedGrid.Position = UDim2.new(0, 16, 0, 54)
SupportedGrid.BackgroundTransparency = 1
SupportedGrid.BorderSizePixel = 0
SupportedGrid.ScrollBarThickness = 4
SupportedGrid.ScrollBarImageColor3 = Color3.fromRGB(70, 70, 70)
SupportedGrid.AutomaticCanvasSize = Enum.AutomaticSize.Y
SupportedGrid.CanvasSize = UDim2.new(0, 0, 0, 0)
SupportedGrid.ZIndex = 41
SupportedGrid.Parent = SupportedGamesPanel

local SupportedGridLayout = Instance.new("UIGridLayout")
SupportedGridLayout.CellSize = UDim2.new(0, 170, 0, 148)
SupportedGridLayout.CellPadding = UDim2.new(0, 14, 0, 14)
SupportedGridLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
SupportedGridLayout.VerticalAlignment = Enum.VerticalAlignment.Top
SupportedGridLayout.SortOrder = Enum.SortOrder.LayoutOrder
SupportedGridLayout.Parent = SupportedGrid

local SupportedGridPadding = Instance.new("UIPadding")
SupportedGridPadding.PaddingLeft = UDim.new(0, 4)
SupportedGridPadding.PaddingRight = UDim.new(0, 4)
SupportedGridPadding.PaddingTop = UDim.new(0, 4)
SupportedGridPadding.PaddingBottom = UDim.new(0, 14)
SupportedGridPadding.Parent = SupportedGrid

local function makeSupportedGameCard(gameData, order)
    local card = Instance.new("Frame")
    card.Name = "SupportedGame_" .. tostring(order)
    card.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
    card.BorderSizePixel = 0
    card.ClipsDescendants = true
    card.LayoutOrder = order
    card.ZIndex = 42
    card.Parent = SupportedGrid

    local cardCorner = Instance.new("UICorner")
    cardCorner.CornerRadius = UDim.new(0, 10)
    cardCorner.Parent = card

    local cardStroke = Instance.new("UIStroke")
    cardStroke.Color = Color3.fromRGB(45, 45, 45)
    cardStroke.Thickness = 1
    cardStroke.Parent = card

    local thumbnail = Instance.new("ImageLabel")
    thumbnail.Size = UDim2.new(1, 0, 1, -34)
    thumbnail.BackgroundColor3 = Color3.fromRGB(12, 12, 12)
    thumbnail.BorderSizePixel = 0
    thumbnail.ScaleType = Enum.ScaleType.Crop
    thumbnail.ZIndex = 43
    thumbnail.Parent = card
    thumbnail.Image = loadRemoteAsset("supported_game_" .. tostring(order) .. ".png", gameData.Image, "https://raw.githubusercontent.com/Yousoterium/Sotarium/main/images/game1.png")

    local titleBar = Instance.new("Frame")
    titleBar.Size = UDim2.new(1, 0, 0, 34)
    titleBar.Position = UDim2.new(0, 0, 1, -34)
    titleBar.BackgroundColor3 = Color3.fromRGB(8, 8, 8)
    titleBar.BorderSizePixel = 0
    titleBar.ZIndex = 44
    titleBar.Parent = card

    local title = Instance.new("TextLabel")
    title.Size = UDim2.new(1, -12, 1, 0)
    title.Position = UDim2.new(0, 6, 0, 0)
    title.BackgroundTransparency = 1
    title.Font = Enum.Font.GothamBold
    title.Text = gameData.Name
    title.TextColor3 = Color3.fromRGB(255, 255, 255)
    title.TextSize = 11
    title.TextTruncate = Enum.TextTruncate.AtEnd
    title.TextXAlignment = Enum.TextXAlignment.Center
    title.ZIndex = 45
    title.Parent = titleBar
end

for index, gameData in ipairs(SupportedGamesList) do
    makeSupportedGameCard(gameData, index)
end

local isSupportedGamesOpen = false
local function closeSupportedGames()
    if not isSupportedGamesOpen then return end
    isSupportedGamesOpen = false
    SupportedGamesPanel.Visible = false
    setMenuControlsEnabled(true)
end

SupportedBackButton.MouseEnter:Connect(function()
    TweenService:Create(SupportedBackButton, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(38, 38, 38)}):Play()
end)
SupportedBackButton.MouseLeave:Connect(function()
    TweenService:Create(SupportedBackButton, TweenInfo.new(0.15), {BackgroundColor3 = Color3.fromRGB(28, 28, 28)}):Play()
end)
SupportedBackButton.MouseButton1Click:Connect(closeSupportedGames)

SupportedGamesButton.MouseButton1Click:Connect(function()
    if isSupportedGamesOpen then return end
    isSupportedGamesOpen = true
    setMenuControlsEnabled(false)
    SupportedGamesPanel.Visible = true
end)

-- ===========================================
-- ===========================================
-- Universal Cryptographic & Remote Key Verification Engine
-- ===========================================
local function computeKeySignature(g1, g2)
    local salt = "SOTARIUM_2026"
    local full = g1 .. g2 .. salt
    local chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    local numChars = #chars
    local h1, h2, h3 = 17, 37, 79
    for i = 1, #full do
        local code = string.byte(full, i)
        h1 = (h1 * 31 + code) % numChars
        h2 = (h2 * 37 + code * i) % numChars
        h3 = (h3 * 41 + code * (i + 2)) % numChars
    end
    local c1 = string.sub(chars, h1 + 1, h1 + 1)
    local c2 = string.sub(chars, h2 + 1, h2 + 1)
    local c3 = string.sub(chars, h3 + 1, h3 + 1)
    return c1 .. c2 .. c3
end

local KEY_VERIFY_URL = "https://sotarium.vercel.app/api/verify-key"

local function verifyKeyRemote(keyToVerify)
    local normalized = keyToVerify:gsub("%s+", ""):upper()
    if normalized == "" then
        return false, "Please enter a key"
    end

    local player = Players.LocalPlayer
    if not player then
        return false, "Roblox account unavailable"
    end

    local requestOptions = {
        Url = KEY_VERIFY_URL,
        Method = "POST",
        Headers = { ["Content-Type"] = "application/json" },
        Body = HttpService:JSONEncode({
            key = normalized,
            roblox_id = tostring(player.UserId),
            roblox_username = tostring(player.Name)
        })
    }

    local verifyGetUrl = KEY_VERIFY_URL
        .. "?key=" .. HttpService:UrlEncode(normalized)
        .. "&roblox_id=" .. HttpService:UrlEncode(tostring(player.UserId))
        .. "&roblox_username=" .. HttpService:UrlEncode(tostring(player.Name))

    local ok, response = pcall(function()
        if syn and syn.request then
            return syn.request(requestOptions)
        elseif http and http.request then
            return http.request(requestOptions)
        elseif http_request then
            return http_request(requestOptions)
        elseif request then
            return request(requestOptions)
        elseif HttpService and type(HttpService.GetAsync) == "function" then
            return { StatusCode = 200, Body = HttpService:GetAsync(verifyGetUrl) }
        elseif game and type(game.HttpGet) == "function" then
            return { StatusCode = 200, Body = game:HttpGet(verifyGetUrl, true) }
        end
        return nil
    end)

    if not ok or not response or response.StatusCode ~= 200 or type(response.Body) ~= "string" then
        return false, "Could not verify key. Please try again."
    end

    local decodedOk, result = pcall(function()
        return HttpService:JSONDecode(response.Body)
    end)

    if not decodedOk or type(result) ~= "table" then
        return false, "Could not verify key. Please try again."
    end

    if result.valid == true then
        return true, result.message or "Access granted"
    end

    return false, result.message or "Key Invalid"
end

-- ===========================================
-- Provider Overlay Animation Screen
-- ===========================================
local Overlay = Instance.new("Frame")
Overlay.Name = "ProviderOverlay"
Overlay.Size = UDim2.new(1, 0, 1, 0)
Overlay.Position = UDim2.new(0, 0, 0, 0)
Overlay.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
Overlay.BackgroundTransparency = 1
Overlay.BorderSizePixel = 0
Overlay.ClipsDescendants = true
Overlay.Visible = false
Overlay.ZIndex = 20
Overlay.Parent = MainFrame

local OverlayCorner = Instance.new("UICorner")
OverlayCorner.CornerRadius = UDim.new(0, 14)
OverlayCorner.Parent = Overlay

local SpinnerHolder = Instance.new("Frame")
SpinnerHolder.Name = "SpinnerHolder"
SpinnerHolder.Size = UDim2.new(0, 48, 0, 48)
SpinnerHolder.Position = UDim2.new(0.5, 0, 0.40, 0)
SpinnerHolder.AnchorPoint = Vector2.new(0.5, 0.5)
SpinnerHolder.BackgroundTransparency = 1
SpinnerHolder.ZIndex = 21
SpinnerHolder.Parent = Overlay

local SpinnerCircle = Instance.new("Frame")
SpinnerCircle.Name = "SpinnerCircle"
SpinnerCircle.Size = UDim2.new(1, 0, 1, 0)
SpinnerCircle.Position = UDim2.new(0.5, 0, 0.5, 0)
SpinnerCircle.AnchorPoint = Vector2.new(0.5, 0.5)
SpinnerCircle.BackgroundTransparency = 1
SpinnerCircle.ZIndex = 22
SpinnerCircle.Parent = SpinnerHolder

local SpinnerCorner = Instance.new("UICorner")
SpinnerCorner.CornerRadius = UDim.new(1, 0)
SpinnerCorner.Parent = SpinnerCircle

local SpinnerStroke = Instance.new("UIStroke")
SpinnerStroke.Color = Color3.fromRGB(255, 255, 255)
SpinnerStroke.Thickness = 3
SpinnerStroke.Parent = SpinnerCircle

local SpinnerNotch = Instance.new("Frame")
SpinnerNotch.Size = UDim2.new(0.55, 0, 0.55, 0)
SpinnerNotch.Position = UDim2.new(0.5, 0, -0.05, 0)
SpinnerNotch.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
SpinnerNotch.BorderSizePixel = 0
SpinnerNotch.ZIndex = 23
SpinnerNotch.Parent = SpinnerCircle

local SuccessBadge = Instance.new("Frame")
SuccessBadge.Name = "SuccessBadge"
SuccessBadge.Size = UDim2.new(0, 52, 0, 52)
SuccessBadge.Position = UDim2.new(0.5, 0, 0.40, 0)
SuccessBadge.AnchorPoint = Vector2.new(0.5, 0.5)
SuccessBadge.BackgroundColor3 = Color3.fromRGB(34, 215, 64)
SuccessBadge.BorderSizePixel = 0
SuccessBadge.BackgroundTransparency = 1
SuccessBadge.Visible = false
SuccessBadge.ZIndex = 24
SuccessBadge.Parent = Overlay

local SuccessCorner = Instance.new("UICorner")
SuccessCorner.CornerRadius = UDim.new(1, 0)
SuccessCorner.Parent = SuccessBadge

local SuccessIcon = Instance.new("ImageLabel")
SuccessIcon.Name = "SuccessIcon"
SuccessIcon.Size = UDim2.new(0, 28, 0, 28)
SuccessIcon.Position = UDim2.new(0.5, 0, 0.5, 0)
SuccessIcon.AnchorPoint = Vector2.new(0.5, 0.5)
SuccessIcon.BackgroundTransparency = 1
SuccessIcon.Image = LucideIcons["check"]
SuccessIcon.ImageColor3 = Color3.fromRGB(255, 255, 255)
SuccessIcon.ImageTransparency = 1
SuccessIcon.ZIndex = 25
SuccessIcon.Parent = SuccessBadge

local OverlayStatus = Instance.new("TextLabel")
OverlayStatus.Name = "OverlayStatus"
OverlayStatus.Size = UDim2.new(1, -40, 0, 32)
OverlayStatus.Position = UDim2.new(0.5, 0, 0.53, 0)
OverlayStatus.AnchorPoint = Vector2.new(0.5, 0.5)
OverlayStatus.BackgroundTransparency = 1
OverlayStatus.Font = Enum.Font.GothamBlack
OverlayStatus.Text = "Verifying..."
OverlayStatus.TextColor3 = Color3.fromRGB(255, 255, 255)
OverlayStatus.TextSize = 20
OverlayStatus.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OverlayStatus.TextStrokeTransparency = 0.35
OverlayStatus.TextXAlignment = Enum.TextXAlignment.Center
OverlayStatus.TextYAlignment = Enum.TextYAlignment.Center
OverlayStatus.ZIndex = 21
OverlayStatus.Parent = Overlay

local isSpinning = false
local function runSpinner()
    isSpinning = true
    task.spawn(function()
        while isSpinning do
            SpinnerCircle.Rotation = (SpinnerCircle.Rotation + 8) % 360
            task.wait(0.016)
        end
    end)
end

-- ===========================================
-- Key Validation Logic (Checks Supabase Provider Keys & Test Key)
-- ===========================================
local isVerifying = false

SubmitButton.MouseButton1Click:Connect(function()
    if isVerifying then return end
    local enteredKey = KeyTextBox.Text:gsub("%s+", "")
    
    if #enteredKey == 0 then
        showNotification("Please enter a key", "warning", 2.5)
        return
    end

    isVerifying = true
    Overlay.Visible = true
    SpinnerHolder.Visible = true
    SpinnerCircle.Size = UDim2.new(1, 0, 1, 0)
    SpinnerCircle.BackgroundTransparency = 1
    SpinnerStroke.Transparency = 0
    SuccessBadge.Visible = false
    SuccessBadge.Size = UDim2.new(0, 0, 0, 0)
    SuccessBadge.Rotation = -35
    SuccessBadge.BackgroundTransparency = 1
    SuccessIcon.ImageTransparency = 1
    OverlayStatus.Text = "Verifying..."
    OverlayStatus.TextColor3 = Color3.fromRGB(255, 255, 255)
    Overlay.BackgroundTransparency = 1
    OverlayStatus.TextTransparency = 1
    
    TweenService:Create(Overlay, TweenInfo.new(0.35), {BackgroundTransparency = 0}):Play()
    TweenService:Create(OverlayStatus, TweenInfo.new(0.35), {TextTransparency = 0}):Play()
    runSpinner()

    -- Perform asynchronous key validation (Extended duration for satisfying animation)
    task.spawn(function()
        local isValidKey, statusMessage = verifyKeyRemote(enteredKey)
        task.wait(2.2)
        
        if isValidKey then
            isSpinning = false
            
            -- Smooth shrink and fade out of spinner
            TweenService:Create(SpinnerCircle, TweenInfo.new(0.3, Enum.EasingStyle.Back, Enum.EasingDirection.In), {
                Size = UDim2.new(0, 0, 0, 0)
            }):Play()
            local fadeOutSpinner = TweenService:Create(SpinnerStroke, TweenInfo.new(0.25), {
                Transparency = 1
            })
            fadeOutSpinner:Play()
            fadeOutSpinner.Completed:Connect(function()
                SpinnerHolder.Visible = false
            end)
            
            task.wait(0.1)
            
            -- Smooth elastic spring bounce animation for verified checkmark
            SuccessBadge.Visible = true
            SuccessBadge.Size = UDim2.new(0, 0, 0, 0)
            SuccessBadge.Rotation = -35
            
            TweenService:Create(SuccessBadge, TweenInfo.new(0.65, Enum.EasingStyle.Elastic, Enum.EasingDirection.Out), {
                BackgroundTransparency = 0,
                Size = UDim2.new(0, 52, 0, 52),
                Rotation = 0
            }):Play()

            TweenService:Create(SuccessIcon, TweenInfo.new(0.45, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {
                ImageTransparency = 0
            }):Play()

            OverlayStatus.Text = "Success"
            OverlayStatus.TextColor3 = Color3.fromRGB(46, 230, 96)
            showNotification(statusMessage or "Access granted", "success", 3)
            
            task.wait(1.6)
            local closeTween = TweenService:Create(MainFrame, TweenInfo.new(0.4, Enum.EasingStyle.Back, Enum.EasingDirection.In), {
                Size = UDim2.new(0, 0, 0, 0),
                Position = UDim2.new(0.5, 0, 0.5, 0)
            })
            closeTween:Play()
            closeTween.Completed:Connect(function()
                ScreenGui:Destroy()
-- __SOTARIUM_GENERATED_LAUNCH_PAYLOAD__
            end)
        else
            -- Invalid Key
            isSpinning = false
            TweenService:Create(Overlay, TweenInfo.new(0.2), {BackgroundTransparency = 1}):Play()
            task.wait(0.2)
            Overlay.Visible = false
            isVerifying = false
            
            showNotification(statusMessage or "Invalid key", "error", 2.5)
            
            local originalPos = KeyInputFrame.Position
            for _ = 1, 2 do
                TweenService:Create(KeyInputFrame, TweenInfo.new(0.04), {Position = UDim2.new(0, 6, 0, 0)}):Play()
                task.wait(0.04)
                TweenService:Create(KeyInputFrame, TweenInfo.new(0.04), {Position = UDim2.new(0, -6, 0, 0)}):Play()
                task.wait(0.04)
            end
            KeyInputFrame.Position = originalPos
        end
    end)
end)

-- Get Key Action
GetKeyButton.MouseButton1Click:Connect(function()
    if setclipboard then
        setclipboard("https://sotarium.vercel.app/")
    end
    showNotification("Website link copied", "key", 2.5)
end)

-- Dragging Window Logic
local dragging = false
local dragInput, dragStart, startPos

local function updateDrag(input)
    local delta = input.Position - dragStart
    MainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
end

TopBar.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
        dragging = true
        dragStart = input.Position
        startPos = MainFrame.Position
        input.Changed:Connect(function()
            if input.UserInputState == Enum.UserInputState.End then
                dragging = false
            end
        end)
    end
end)

TopBar.InputChanged:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
        dragInput = input
    end
end)

UserInputService.InputChanged:Connect(function(input)
    if input == dragInput and dragging and not isMaximized then
        updateDrag(input)
    end
end)

-- ===========================================
-- Trigger Launched Notification on Startup
-- ===========================================
task.spawn(function()
    task.wait(0.1)
    showNotification("Launched", "rocket", 2.5)
end)
